# ============================================================================
# Chezmoi Data File - Host Themes & Shared Configuration
# ============================================================================
# This file defines per-host color palettes and shared settings.
# Access in templates via: {{ .hosts.studio.primary }}

# Host definitions with distinct color palettes
hosts:
  # macOS machines
  studio:
    label: "studio"
    os: "macos"
    icon: ""
    theme: "ocean"
    # Ocean blue palette - monochromatic blue
    primary: "#569edf"
    secondary: "#4d8fcc"
    accent: "#3a7cb8"
    warning: "#e5c07b"
    error: "#e06c75"
    muted: "#5c6370"
    bg: "#282c34"
    bg_dark: "#222436"
    fg: "#c8ccd4"
    fg_bright: "#ffffff"

  mbp:
    label: "mbp"
    os: "macos"
    icon: ""
    theme: "forest"
    # Forest green palette - monochromatic green
    primary: "#98c379"
    secondary: "#7da662"
    accent: "#5f8a4a"
    warning: "#e5c07b"
    error: "#e06c75"
    muted: "#5c6370"
    bg: "#282c34"
    bg_dark: "#222436"
    fg: "#abb2bf"
    fg_bright: "#ffffff"

  # Arch Linux machines
  archdev:
    label: "archdev"
    os: "arch"
    icon: ""
    theme: "crimson"
    # Crimson red palette - monochromatic red
    primary: "#e06c75"
    secondary: "#be5046"
    accent: "#943d3d"
    warning: "#e5c07b"
    error: "#ff6b6b"
    muted: "#5c6370"
    bg: "#282c34"
    bg_dark: "#21252b"
    fg: "#abb2bf"
    fg_bright: "#ffffff"

  archdev101:
    label: "archdev101"
    os: "arch"
    icon: ""
    theme: "mauve"
    # Mauve palette - monochromatic purple/mauve
    primary: "#c678dd"
    secondary: "#a855a8"
    accent: "#8a4488"
    warning: "#e5c07b"
    error: "#e06c75"
    muted: "#5c6370"
    bg: "#282c34"
    bg_dark: "#21252b"
    fg: "#abb2bf"
    fg_bright: "#ffffff"

  # Ubuntu machine
  ubuntu103:
    label: "ubuntu103"
    os: "ubuntu"
    icon: ""
    theme: "ember"
    # Ember orange palette - monochromatic orange
    primary: "#d19a66"
    secondary: "#b8834d"
    accent: "#9a6a3a"
    warning: "#e5c07b"
    error: "#e06c75"
    muted: "#5c6370"
    bg: "#282c34"
    bg_dark: "#21252b"
    fg: "#abb2bf"
    fg_bright: "#ffffff"

# Default/fallback theme (used if host not recognized)
default:
  label: "unknown"
  os: "linux"
  theme: "default"
  primary: "#89b4fa"
  secondary: "#94e2d5"
  accent: "#f5c2e7"
  warning: "#f9e2af"
  error: "#f38ba8"
  muted: "#6c7086"
  bg: "#1e1e2e"
  bg_dark: "#11111b"
  fg: "#cdd6f4"
  fg_bright: "#ffffff"

# Shared tool settings (not host-specific)
tools:
  editor: "nvim"
  pager: "bat"
  shell: "zsh"

# Package lists per OS
packages:
  common:
    - zsh
    - git
    - curl
    - tmux
    - neovim
    - starship
    - ripgrep
    - fd
    - fzf
    - zoxide
    - bat
    - eza
    - jq
    - tree

  macos_extra:
    - gh
    - yazi
    - chafa
    - ffmpegthumbnailer
    - poppler
    - imagemagick

  arch_extra:
    - github-cli
    - yazi
    - chafa
    - ffmpegthumbnailer
    - poppler
    - imagemagick
    - wl-clipboard
    - xclip

  ubuntu_extra:
    - gh
    - chafa
    - ffmpeg
    - poppler-utils
    - imagemagick
    - xclip
    - wl-clipboard
